broken_employee_data.csv:
  filename: broken_employee_data.csv
  inferred: false

  schema:
    id:
      type: int
      nullable: false

    name:
      type: str
      nullable: false

    age:
      type: int
      nullable: false
      min: 0
      max: 150

    salary:
      type: float
      nullable: false
      min: 0
      max: 999999

    department:
      type: str
      nullable: false
      literal_values:
        - HR
        - Sales

  transformations:
    - operation: coerce_numeric
      columns:
        - age
        - salary
    - operation: rename_to_snake_case
