schema:
  id:
    type: int
    nullable: false

  salary:
    type: float
    nullable: false
    min: 0

  employeeName:
    type: str
    nullable: false
    min_length: 1

  employeeAge:
    type: int
    nullable: false
    min: 0

transformations:
  - operation: create_unique_employee_id
    selection: infer
    description: Create a hash id
  - operation: coerce_employee_age_to_int
    selection: infer
    description: Coerce age to int
